on:
  workflow_call:
    secrets:
      projectToken:
        required: true

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.actor != 'renovate[bot]' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - name: publish chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
